---
- name: Installing Windows Updates
  win_updates:
    category_names: "{{ category_names[0] }}"
    register: update_result

- name: Reboot if needed
  win_shell:
  when: update_result.reboot_required
  ignore_errors: yes